version: "3"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./rsa_pub.pem:/etc/grafana/keys/rsa_pub.pem
  nginx:
    image: nginx
    ports:
      - 9090:9090
    volumes:
      - ./mysite.conf:/etc/nginx/conf.d/mysite.conf
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9090:9090
  web:
    build: '.'
    ports:
      - 5000:5000
    volumes:
      - ./rsa.pem:/srv/rsa.pem
